name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
#     - name: Install dependencies
#       run: go get github.com/google/uuid

    - name: Run map reduce lab tests
      run: |
        go get github.com/google/uuid
        cd src/main/
        chmod u+x test-mr.sh
        ./test-mr.sh
