name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run map reduce lab tests
      run: |
        cd src/main/
        chmod u+x test-mr.sh
        ./test-mr.sh

    - name: Run 2A raft leader election tests
      run: |
        cd src/raft/
        for i in $(seq 1 10); do go test -run TestManyElections2A; done
